Post/urls.py
from django.conf.urls import url
from.import views

app_name='Post'

urlpatterns = [
    url(r'^$', views.all_posts, name='all_posts'),
    url(r'^(?P<id>\d+)$', views.post, name='post'),
    url(r'^create$', views.create_post, name='create_post'),
    url(r'^(?P<id>\d+)/edit$', views.edit_post, name='edit_post'),

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Post.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField



class Post(models.Model):
    user = models.ForeignKey(User, on_delete='None')
    title = models.CharField(max_length=50)
    content = RichTextField()
    img = models.ImageField(upload_to='post_img/', default='post_img/default.jpg')
    created = models.DateTimeField(default=timezone.now)

    active =models.BooleanField(default=True)

    def __str__(self):
        return self.title

Post/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget



class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ['title', 'content', 'img']

Post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm
from django.contrib import messages



def all_posts(request):
    all_posts= Post.objects.filter(active=True)

    context={
        'all_posts' : all_posts,
    }

    return render (request, 'all_posts.html', context)



def post(request, id):
    #post = Post.objects.get(id=id)
    post = get_object_or_404 (Post, id=id)
    context= {
        'post' : post,
    }

    return render(request, 'detail.html', context)




def create_post(request):
     if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Post Created Successfully')
            return redirect('/')

     else:
        form = PostForm()

     context={
        'form' : form ,
    }

     return render(request, 'create.html', context)



def edit_post(request, id):
    post = get_object_or_404(Post , id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/')


    else:
        form = PostForm(instance=post)

    context={
        'form' : form ,
    }

    return render(request, 'edit.html', context)

Post/templates/all_posts.html
{% extends "base.html" %}
{% load  static %}

{% block body  %}

<div class="jumbotron banner">
  <a class="btn btn-primary btn-lg" href="{% url 'blog:create_post' %}" role="button">Add new Post</a>
</div>


        {% for post in all_posts %}
      <div class="col-md--4">
          <div class="card">
            {% if post.img %}
          <img  class="card-img-top"  src="{{post.img.url}}" alt="card-img-top">
            {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{post.title}}</h5>
            <p class="card-text">{{post.content|safe|truncatewords:10}}</p>
            <a href="{% url 'blog:post' post.id %}" class="btn btn-primary">Know More</a>
          </div>
        </div>
          {% endfor %}

{% endblock body %}

Post/templates/create.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body  %}
<div class="blog_form">
  <form method="post" enctype="multipart/fom-date">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Save Post</button>
    {% endbuttons %}
  </form>

</div>
{% endblock body %}

Post/templates/detail.html
{% extends "base.html" %}
{% load  static %}

{% block body  %}
<div class="jumbotron banner">
  <a class="btn btn-primary btn-lg" href="{% url 'blog:edit_post' post.id %}" role="button">Edit This Post</a>
</div>

          <div class="card single_post">
          <img src="{{post.img.url}}" class="card-img-top" alt="card-img-top">
          <div class="card-body">
            <h5 class="card-title">{{post}}</h5>
            <p class="card-text">{{post.content|safe}}</p>
          </div>
{% endblock body %}

Post/templates/edit.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body  %}
<div class="blog_form">
  <form method="post" enctype="multipart/fom-date">
    {% csrf_token %}
    {{ form.media }}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Save Post</button>
    {% endbuttons %}
  </form>
</div>
{% endblock body %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home_static/css/style.css'%}">
    <title>Python News</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Python News</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
    <div class="massage-div">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
    </div>
    <div class="container">
      <div class="row mt--4">

          {% block body  %}
          {% endblock body %}

  </div>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>